### PR TITLE
Add Umo Editor

### PR DESCRIPTION
**Pull request by umodoc**
Umo Editor is open-source document editor based on Vue3 and Tiptap. Umo Editor provides comprehensive document editing capabilities and AI creation features, supports pagination, supports Markdown syntax, offers basic rich text editing functions, allows for the insertion of various node types in multiple formats, provides a variety of practical tools, and supports setting page styles. It also supports exporting in various formats, printing and print preview, block-level document editing, adding custom extensions, multi-language settings, and a dark theme.

- [Documentation](https://editor.umodoc.com/en/docs)
- [Playground](https://demo.umodoc.com/editor?pane=hide&lang=en-US)

### CODE REVIEW

**Comment by DannyFeliz** [comment]
Great editor, thanks for sharing.

**Comment by umodoc** [comment]
> Great editor, thanks for sharing.


@DannyFeliz 
Thank you for your recognition and affection for Umo Editor! If you encounter any issues or have suggestions during your use, please don't hesitate to bring them up. We are committed to improving and hope to make the Umo Editor even better to meet your needs. Your support is greatly appreciated!

**Comment by nperez0111** [comment]
Fantastic editor, clearly a lot of work went into it!

**Comment by Ankit-26** [comment]
@umodoc  can you give some idea about how you implemented the pagination functionality?

**Comment by umodoc** [comment]
> @umodoc can you give some idea about how you implemented the pagination functionality?

@Ankit-26 In simple terms, the pagination functionality is implemented by calculating the DOM width and height of the editor content and the critical point of characters to accurately find the split point, then dividing the document content into multiple segments. However, this method also faces many challenges.

For the specific implementation details, please refer to the following link:https://github.com/umodoc/editor/tree/main/src/extensions/page

**Pull request merged**
